version: "3.9"
services:
  postgres:
    image: 'postgres:13.3'
    environment:
      POSTGRES_DB: "mydb_delivery"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
